name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Wrangler CLI
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
